linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
