linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - revive

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  revive:
    min-confidence: 0.8
